-- MySQL Script generated by MySQL Workbench
-- Fri Jan 23 00:50:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`telefone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `idtelefone` INT NOT NULL,
  `dd` INT NOT NULL,
  `codigo` INT NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtelefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contato` (
  `idcontato` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `telefone_idtelefone` INT NOT NULL,
  PRIMARY KEY (`idcontato`),
  INDEX `fk_contato_telefone_idx` (`telefone_idtelefone` ASC) VISIBLE,
  CONSTRAINT `fk_contato_telefone`
    FOREIGN KEY (`telefone_idtelefone`)
    REFERENCES `mydb`.`telefone` (`idtelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria_has_contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria_has_contato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria_has_contato` (
  `Categoria_idCategoria` INT NOT NULL,
  `contato_idcontato` INT NOT NULL,
  PRIMARY KEY (`Categoria_idCategoria`, `contato_idcontato`),
  INDEX `fk_Categoria_has_contato_contato1_idx` (`contato_idcontato` ASC) VISIBLE,
  INDEX `fk_Categoria_has_contato_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_has_contato_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_contato_contato1`
    FOREIGN KEY (`contato_idcontato`)
    REFERENCES `mydb`.`contato` (`idcontato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
